package se.kth.iv1350.posSystem.integration;

import se.kth.iv1350.posSystem.dto.ReceiptDTO;

/**
 * A listener interface used for receiving information of revenue generated by a sale.
 */
public interface SystemHandlerObserver {
	/**
	 * Called when transaction is finalized and logs are updated.
	 * @param receiptDTO The transaction information, including revenue generated by the sale.
	 */
	void updateLogs(ReceiptDTO receiptDTO);
}
