package se.kth.iv1350.posSystem.view;

import se.kth.iv1350.posSystem.integration.SaleLogObserver;
import se.kth.iv1350.posSystem.model.SaleDTO;
import se.kth.iv1350.posSystem.utilities.Amount;
import se.kth.iv1350.posSystem.utilities.TimeAndDate;

/**
 * Class that shows the revenue generated by sales and prints out the current total revenue.
 */
public class TotalRevenueView implements SaleLogObserver {
    private Amount totalRevenue = new Amount(0);

    public void updateLogs(SaleDTO saleDTO) { // Duplicate code... Approach to solve?
        TimeAndDate timeAndDate = new TimeAndDate();
        this.totalRevenue = this.totalRevenue.plus(saleDTO.getTotalPrice());
        revenuePrinter(timeAndDate);
    }

    private void revenuePrinter(TimeAndDate timeAndDate) { // Duplicate code... Approach to solve?
        System.out.println("\n-------------------------------------------------");
        System.out.println("Revenue at " + timeAndDate.getTimeAndDate() + ": " + this.totalRevenue);
        System.out.println("-------------------------------------------------\n");
    }
}
