package se.kth.iv1350.posSystem.view;

import se.kth.iv1350.posSystem.integration.SaleLogObserver;
import se.kth.iv1350.posSystem.model.SaleDTO;
import se.kth.iv1350.posSystem.utilities.Amount;
import se.kth.iv1350.posSystem.utilities.FileLogger;
import se.kth.iv1350.posSystem.utilities.TimeAndDate;

/**
 * Class that shows the revenue generated by sales and outputs the current total revenue to a text file.
 */
public class TotalRevenueFileOutput implements SaleLogObserver {
    private Amount totalRevenue = new Amount(0);
    private final static String REVENUE_FILE_PATH = "Seminar4/textFiles/totalRevenue.txt";
    private final FileLogger fileLogger = new FileLogger(REVENUE_FILE_PATH);

    public void updateLogs(SaleDTO saleDTO) { // Duplicate code... Approach to solve?
        TimeAndDate timeAndDate = new TimeAndDate();
        this.totalRevenue = this.totalRevenue.plus(saleDTO.getTotalPrice());
        String logEntry = "Revenue at " + timeAndDate.getTimeAndDate() + ": " + this.totalRevenue;
        fileLogger.addEntryToLog(logEntry);
    }
}