package se.kth.iv1350.posSystem.view;

import se.kth.iv1350.posSystem.dto.ReceiptDTO;
import se.kth.iv1350.posSystem.integration.SystemHandlerObserver;
import se.kth.iv1350.posSystem.utilities.Amount;
import se.kth.iv1350.posSystem.utilities.TimeAndDate;

/**
 * Class that shows the revenue generated by sales and prints out the current total revenue.
 */
public class TotalRevenueView implements SystemHandlerObserver {
    private Amount totalRevenue = new Amount(0);

    /**
     * Prints out the time of update and the total revenue generated since program startup
     *
     * @param receiptDTO The transaction information, including revenue generated by the sale.
     */
    public void updateLogs(ReceiptDTO receiptDTO) {
        TimeAndDate timeAndDate = new TimeAndDate();
        this.totalRevenue = this.totalRevenue.plus(receiptDTO.getTotalPriceAfterDiscount());
        revenuePrinter(timeAndDate);
    }

    private void revenuePrinter(TimeAndDate timeAndDate) {
        System.out.println("\n-------------------------------------------------");
        System.out.println("Revenue at " + timeAndDate.getTimeAndDate() + ": " + this.totalRevenue);
        System.out.println("-------------------------------------------------\n");
    }
}
