package se.kth.iv1350.posSystem.model;

import se.kth.iv1350.posSystem.utilities.Amount;

/**
 * A listener interface used for receiving information of revenue generated by a sale.
 */
public interface PaymentObserver {
	/**
	 * Called when transaction is finalized and logs are updated.
	 * @param revenueToAdd The transaction information, including revenue generated by the sale.
	 */
	void setAmountPaidAndChange(Amount revenueToAdd);
}