package se.kth.iv1350.posSystem.integration;

import se.kth.iv1350.posSystem.model.SaleDTO;

/**
 * A listener interface used for receiving information of revenue generated by a sale.
 */
public interface SaleLogObserver {
    /**
     * Called when transaction is finalized and logs are updated.
     * @param saleDTO The transaction information, including revenue generated by the sale.
     */
    void updateLogs(SaleDTO saleDTO);
}
