package se.kth.iv1350.posSystem.view;

import se.kth.iv1350.posSystem.model.Revenue;
import se.kth.iv1350.posSystem.utilities.Amount;

/**
 * Class that shows the revenue generated by sales and prints out the current total revenue.
 */
public class TotalRevenueView extends Revenue {

	protected void outputTotalRevenue(String timeAndDateOfLastSale, Amount totalRevenue) {
		System.out.println("\n*************************************************");
		System.out.println("Revenue at " + timeAndDateOfLastSale + ": " + totalRevenue);
		System.out.println("*************************************************");
	}

	protected void handleException(Exception exception) {
		System.out.println("\n*************************************************");
		System.out.println("Error: Could not get total revenue");
		System.out.println("*************************************************");
	}
}
